### ISSUE TITLE
Feature Request: Voice recording

### ISSUE THREAD

**Issue by GuteIdee** [ericfabreu/WearFlashcards#5]
It would be very usefull - f.e. to teach kids - to have the possibility of voice recording on every single flashcard. Not "Text to Speech", because it will have often a wrong pronunciation.

**Comment by ericfabreu** [comment]
Sorry for the delay in replying. While I do think that this would be a great feature to have in a flashcard app, many Android Wear devices don’t have speakers, which would make it difficult or unintuitive to study audio cards on them (it would only work if the user pairs the watch if a Bluetooth speaker). It would also take much longer to load the card on the watch if there were voice recordings in addition to the text. I could not sync the audio cards with the watch, but that could be confusing for other users.

If the app wasn’t focused on watches, I’d definitely add this feature as well as an option to create cards using pictures.

**Comment by GuteIdee** [comment]
I am sorry. I did not think about, that your app is mainly for wear.
